redhat/configs: automotive: stop overriding CRYPTO_ECDH
The git history in centos-stream-9/main-automotive is not very useful
with determining why automotive decided to stop inheriting from RHEL on
this config option.

Now, due to TCG_TPM2_HMAC/TCG_TPM being builtin, this config is forced
to builtin, causing make dist-configs to fail for automotive:

    Error: Mismatches found in configuration files for arm64 aarch64-automotive
    Found CONFIG_CRYPTO_ECDH=y after generation, had CONFIG_CRYPTO_ECDH=m in Source tree

Since there's no obvious reason for automotive to make this a module,
let's just ride RHEL's decisions here for now.

Signed-off-by: Andrew Halaney <ahalaney@redhat.com>
Signed-off-by: Julio Faracco <jfaracco@redhat.com>