powerpc: increase MIN RMA size for CAS negotiation
JIRA: https://issues.redhat.com/browse/RHEL-70827

commit fdc44538d57caf4e96f57d5f0d0c89c4aa079f94
Author: Avnish Chouhan <avnish@linux.ibm.com>
Date:   Thu Jan 23 17:12:53 2025 +0530

    powerpc: increase MIN RMA size for CAS negotiation

    Change RMA size from 512 MB to 768 MB which will result
    in more RMA at boot time for PowerPC. When PowerPC LPAR use/uses vTPM,
    Secure Boot or FADump, the 512 MB RMA memory is not sufficient for
    booting. With this 512 MB RMA, GRUB2 run out of memory and unable to
    load the necessary. Sometimes even usage of CDROM which requires more
    memory for installation along with the options mentioned above troubles
    the boot memory and result in boot failures. Increasing the RMA size
    will resolves multiple out of memory issues observed in PowerPC.

    Failure details:

    1. GRUB2

    kern/ieee1275/init.c:550: mm requested region of size 8513000, flags 1
    kern/ieee1275/init.c:563: Cannot satisfy allocation and retain minimum runtime
    space
    kern/ieee1275/init.c:550: mm requested region of size 8513000, flags 0
    kern/ieee1275/init.c:563: Cannot satisfy allocation and retain minimum runtime
    space
    kern/file.c:215: Closing `/ppc/ppc64/initrd.img' ...
    kern/disk.c:297: Closing
    `ieee1275//vdevice/v-scsi
    @30000067/disk@8300000000000000'...
    kern/disk.c:311: Closing
    `ieee1275//vdevice/v-scsi
    @30000067/disk@8300000000000000' succeeded.
    kern/file.c:225: Closing `/ppc/ppc64/initrd.img' failed with 3.
    kern/file.c:148: Opening `/ppc/ppc64/initrd.img' succeeded.
    error: ../../grub-core/kern/mm.c:552:out of memory.

    2. Kernel

    [    0.777633] List of all partitions:
    [    0.777639] No filesystem could mount root, tried:
    [    0.777640]
    [    0.777649] Kernel panic - not syncing: VFS: Unable to mount root fs on "" or unknown-block(0,0)
    [    0.777658] CPU: 17 UID: 0 PID: 1 Comm: swapper/0 Not tainted 6.11.0-0.rc4.20.el10.ppc64le #1
    [    0.777669] Hardware name: IBM,9009-22A POWER9 (architected) 0x4e0202 0xf000005 of:IBM,FW950.B0 (VL950_149) hv:phyp pSeries
    [    0.777678] Call Trace:
    [    0.777682] [c000000003db7b60] [c000000001119714] dump_stack_lvl+0x88/0xc4 (unreliable)
    [    0.777700] [c000000003db7b90] [c00000000016c274] panic+0x174/0x460
    [    0.777711] [c000000003db7c30] [c00000000200631c] mount_root_generic+0x320/0x354
    [    0.777724] [c000000003db7d00] [c0000000020066f8] prepare_namespace+0x27c/0x2f4
    [    0.777735] [c000000003db7d90] [c000000002005824] kernel_init_freeable+0x254/0x294
    [    0.777747] [c000000003db7df0] [c00000000001131c] kernel_init+0x30/0x1c4
    [    0.777757] [c000000003db7e50] [c00000000000debc] ret_from_kernel_user_thread+0x14/0x1c
    [    0.777768] --- interrupt: 0 at 0x0
    [    0.784238] pstore: backend (nvram) writing error (-1)
    [    0.790447] Rebooting in 10 seconds..

    Signed-off-by: Avnish Chouhan <avnish@linux.ibm.com>
    Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
    Link: https://patch.msgid.link/20250123114254.200527-4-sourabhjain@linux.ibm.com

Signed-off-by: Mamatha Inamdar <minamdar@redhat.com>